Ini/feature/command history
AlbertaSat/ex3_ground_station pull request #13
Opened 2024-06-17 18:20 UTC by iniadeniyi

2024-06-18 20:33 UTC, dheadrick1618 requested changes
Good work so far! I can't wait to test it myself, but I am a complete stranger to postgres and this stuff right now, so I cant get it to connect to a postgres db properly  :{

2024-06-18 20:33 UTC, dheadrick1618 commented on README.md
> +1. Install PostgreSQL: https://www.postgresql.org/download/
At this point it might be worth us setting up a docker container to handle all this and prevent compatibility issues between OS and peoples working environments.

2024-06-18 20:33 UTC, dheadrick1618 commented on README.md
> +3. Update the db_url in `main.rs` with username, password and db_name
Maybe give an internal like to the src/main in the root project dir as there are many 'main' in this cargo workspace.

2024-06-18 20:33 UTC, dheadrick1618 commented on README.md
> +5. Use sea-orm-cli to run migrations: https://www.sea-ql.org/sea-orm-tutorial/ch01-02-migration-cli.html
Im assuming we still run this even though there is already a 'migration' dir in this PR?

2024-06-18 20:33 UTC, dheadrick1618 commented on README.md
Also please add a section on how to quickly setup a dummy postgres account using the cli tools, and  have the hardcoded db url use those values in the meantime.

2024-06-18 20:33 UTC, dheadrick1618 commented on README.md
> +6. run server: `cargo run`
Running cargo run in both the root project dir and in the ex3_groundstation_dashboard dir gives me the error connecting to database. 

`thread 'main' panicked at src/main.rs:64:19:
Error connecting to database: Connection Error: error returned from database: password authentication failed for user "postgres"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

Could you write in the README how to quickly setup a dummy account with the postgres cli tool etc, so I can be sure I didn't do something wrong (yes I double checked the db url in main :P )

2024-06-23 00:32 UTC, iniadeniyi commented on migration/src/m20240616_000001_create_command_table.rs
A migration is a file that specifies changes to your database schema, such as creating tables or adding columns. Migration files are named with dates to ensure they run in the correct order, avoid conflicts, and provide historical context. So when you run migrations, all the changes are made to your database in the order of their dates.

2024-06-23 00:40 UTC, iniadeniyi commented on README.md
Yes, I will update the README to explain the project hierarchy. 
Regarding the postgres, I am going to use supabase, supabase.com,  to host a remote postgresql server, so that each developer would not need to create their own local postgres service.

2024-06-23 05:25 UTC, closed without merging